CREATE DATABASE scraperdb_dev;
GO

USE scraperdb_dev;
GO

CREATE TABLE media (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    url NVARCHAR(3000) NOT NULL,
    webUrl NVARCHAR(700) NOT NULL,
    isImage BIT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT GETDATE()
);
GO